package org.folg.gedcom.model

object EventFactResources {
    private val en = mapOf(
        "adop" to "Adoption",
        "afn" to "Ancestral File number",
        "anul" to "Annulment",
        "arvl" to "Arrival",
        "attr" to "Attribute",
        "bapm" to "Baptism",
        "barm" to "Bar mitzvah",
        "batm" to "Bat mitzvah",
        "birt" to "Birth",
        "bles" to "Blessing",
        "buri" to "Burial",
        "cast" to "Caste",
        "caus" to "Cause of death",
        "cens" to "Census",
        "chr" to "Christening",
        "claw" to "Common law marriage",
        "color" to "Color",
        "conf" to "Confirmation",
        "crem" to "Cremation",
        "deat" to "Death",
        "death_of_spouse" to "Death of spouse",
        "deed" to "Deed",
        "deg" to "Degree",
        "div" to "Divorce",
        "divf" to "Divorce filing",
        "dprt" to "Departure",
        "dscr" to "Physical description",
        "educ" to "Education",
        "elec" to "Elected",
        "email" to "Email",
        "emig" to "Emigration",
        "empl" to "Employment",
        "enga" to "Engagement",
        "even" to "Event",
        "excm" to "Excommunication",
        "eyes" to "Eyes",
        "fcom" to "First communion",
        "fnrl" to "Funeral",
        "grad" to "Graduation",
        "hair" to "Hair",
        "heig" to "Height",
        "ill" to "Illness",
        "immi" to "Immigration",
        "marb" to "Marriage banns",
        "marc" to "Marriage contract",
        "marl" to "Marriage license",
        "marr" to "Marriage",
        "mars" to "Marriage settlement",
        "mdcl" to "Medical",
        "milt" to "Military",
        "misn" to "Mission",
        "nams" to "Namesake",
        "nati" to "Nationality",
        "natu" to "Naturalization",
        "nchi" to "Number of children",
        "occu" to "Occupation",
        "ordn" to "Ordination",
        "other" to "Other",
        "phon" to "Phone",
        "prob" to "Probate",
        "prop" to "Property",
        "reli" to "Religion",
        "resi" to "Residence",
        "reti" to "Retirement",
        "sepa" to "Separated",
        "sex" to "Sex",
        "ssn" to "Social security number",
        "titl" to "Title",
        "weig" to "Weight",
        "will" to "Will"
    )

    fun getString(key: String): String? {
        // Simple default to English for now as we don't have Locale in common code easily without dependencies
        return en[key]
    }
}
